#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Styling testing and building your project befor commiting'

# Check Prettier
npm run check-format ||
{
    echo 'Prettier Check Failed. Run npm run format, add changes and try commit again' 
    false;
}


# Check ESlint
# npm run check-lint ||
# {
#     echo 'ESLint Check Failed. Make the required changes listed above, add changes and try commit again'
#     false;
# }

# Chacek tsconfig
npm run check-types ||
{
    echo 'Failed type check. Make the Changes require above, add changes and try commit again'
    false;
}

npm run build ||
{
    echo 'Your build failed, view the errors above'
    false;
}

echo 'Success Commite'
